In [3]:
!pip install numpy

In [4]:
import numpy as np 

In [49]:
#PROBLEM 1
# Create a 3x3 matrix of random integers between 1 and 10
mat = np.random.randint(1, 11, (3, 3))
print(mat)

# Extract the first row and first column
first_row = mat[0, 0:]
first_column = mat[0:, 0]
print("\nFirst Row:", first_row)
print("First Column:", first_column)

# Replace all even numbers in the matrix with 0 !!!
mat[mat % 2 == 0] = 0
print("\nMatrix with Even Numbers Replaced by 0:")
print(mat)


[[4 4 4]
 [7 5 5]
 [4 1 6]]

First Row: [4 4 4]
First Column: [4 7 4]

Matrix with Even Numbers Replaced by 0:
[[0 0 0]
 [7 5 5]
 [0 1 0]]


In [65]:
#PROBLEM 2 
mat1 = np.array([[6,9],[5,9]])
mat2 = np.array([[2,5],[8,6]])
#ADDITION
add = mat1 + mat2
print ("matrix additiom:", add )
#ELEMENT-WISE MULTIPLICATION
multi = mat1 * mat2 
print ("\n matrix element-wise multiplication:", multi )
#DOT PRODUCT (MATRIX MULTIPLICATION)
dot_product = mat1.dot(mat2)
print("\nDot Product:")
print(dot_product)
#TRANSPOSE OF MAT1 
transpose1 = np.transpose(mat1)
print("\nTranspose of Matrix A:")
print(transpose1)
#inverse of mat1 !!!
"""
in order to have an inverse it needs to be:
Square (same number of rows and columns )
Non-singular (its determinant is not zero)
"""
if np.linalg.det(mat1) != 0 :
    mat1_inv = np.linalg.inv(mat1)
    mat1_inv_rounded= np.round(mat1_inv,3)
    print ("Inverse of mat1(to three significant figures)]: \n " , (mat1_inv_rounded))
else :
    print (" Matrix is singular and can not be inverted ")



matrix additiom: [[ 8 14]
 [13 15]]

 matrix element-wise multiplication: [[12 45]
 [40 54]]

Dot Product:
[[84 84]
 [82 79]]

Transpose of Matrix A:
[[6 5]
 [9 9]]
Inverse of mat1(to three significant figures)]: 
  [[ 1.    -1.   ]
 [-0.556  0.667]]


In [59]:
#PROBLEM 3
#determinant = np.linalg.det()
#Rank = np.linalg.matrix_rank()
matrix_3x3 = np.array([[2, 4, 1], 
                       [3, 1, 5], 
                       [7, 2, 6]])
determinant = np.linalg.det(matrix_3x3)

matrix_4x4 =  np.array([
                       [22, 14, 10,30], 
                       [13, 11, 15,9], 
                       [17, 22, 16,12],
                       [23,12,34,50]
                       ])
rank_4x4 = np.linalg.matrix_rank(matrix_4x4)

print("3x3 Matrix:")
print(matrix_3x3)
print(f"Determinant: {determinant:.2f}")
print ("4x4 Matrix:")
print (matrix_4x4)
print ("Rank of the 4x4 Matrix=" , rank_4x4 )

3x3 Matrix:
[[2 4 1]
 [3 1 5]
 [7 2 6]]
Determinant: 59.00
4x4 Matrix:
[[22 14 10 30]
 [13 11 15  9]
 [17 22 16 12]
 [23 12 34 50]]
Rank of the 4x4 Matrix= 4


In [61]:
#PROBLEM 4 !!!
# Define the values of x
x_values = np.array([0, 1, 2, -1])

# Calculate the corresponding y values using the equation y = (5 - 2x) / 3
y_values = (5 - 2 * x_values) / 3

# Display the results
list(zip(x_values, y_values))

[(0, 1.6666666666666667),
 (1, 1.0),
 (2, 0.3333333333333333),
 (-1, 2.3333333333333335)]

In [63]:
#PROBLEM 5 (numpy.fill_diagonal)   arange = (start,stop,step)
matrix5 = np.arange(1,26,1).reshape(5,5)
#extracting rows and columns 2 to 4
extract = matrix5[1:4 , 1:4]
#DIAGONAL ELMENTS EQUALS ZERO
np.fill_diagonal(matrix5,0)
print(matrix5)

[[ 0  2  3  4  5]
 [ 6  0  8  9 10]
 [11 12  0 14 15]
 [16 17 18  0 20]
 [21 22 23 24  0]]
